/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CategoriaJpaController;
import controlador.ProductoJpaController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.DetalleVenta;
import modelo.Producto;

/**
 *
 * @author Familia
 */
public class AgregarProducto extends javax.swing.JDialog {

    public ProductoJpaController controladorProductoAgregar = new ProductoJpaController();
    public CategoriaJpaController controladorCategoriaAgregar = new CategoriaJpaController();
    List<Producto> listaProductoAgregar = new ArrayList<>();
    VistaVentas vistaVentas;
    private DetalleVenta nuevoDetalle;
    
    public AgregarProducto(VistaVentas parent, boolean modal) {
        super(parent, modal);
        vistaVentas = parent;
        initComponents();        
        llenarTablaProducto();
        this.setLocationRelativeTo(AgregarProducto.this);//para que aparezca centrado
        this.setResizable(false);//para que no se modifique el tamaño del frame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTablaProducto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("To Japan", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        jLabel1.setText("Agregar Producto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("To Japan", 1, 14)); // NOI18N
        jLabel11.setText("Nombre:");

        jTableTablaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTablaProductoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableTablaProductoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTablaProducto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre)
                    .addComponent(jLabel11)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        String nombre = jTextFieldNombre.getText();
        listaProductoAgregar = controladorProductoAgregar.consultaxNombre(nombre);
        llenarTablaProducto();
        jTextFieldNombre.setText("");
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTableTablaProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTablaProductoMouseClicked
        
        if (evt.getClickCount() == 2) {
            String dato = JOptionPane.showInputDialog("¿Qué cantidad desea comprar?");
            if (dato != null) {
                if (!dato.equals("")) {
                    int cant = Integer.parseInt(dato);
                    if (cant > 0) {
                        int fila = jTableTablaProducto.getSelectedRow();
                        int codigo = Integer.parseInt(jTableTablaProducto.getValueAt(fila, 0).toString());
                        int stock = Integer.parseInt(jTableTablaProducto.getValueAt(fila, 3).toString());                        
                        Producto productoComprar = controladorProductoAgregar.findProducto(codigo);
                        if (productoComprar.getUnidsProducto()>= cant) {
                            int stockResta = stock - cant;
                            jTableTablaProducto.setValueAt(stockResta, fila, 3);
                            DetalleVenta nuevoDetalle = new DetalleVenta();
                            nuevoDetalle.setCantidadDetalle(cant);
                            nuevoDetalle.setIdProducto(productoComprar);
                            try {
                                int descuento = Integer.parseInt(JOptionPane.showInputDialog("Si tiene algún descuento, Agregelo"));
                                nuevoDetalle.setDescuentoDetalle(descuento);
                            } catch (NumberFormatException e) {
                                nuevoDetalle.setDescuentoDetalle(0);

                            }
                            vistaVentas.detalleVenta.add(nuevoDetalle);
                            JOptionPane.showMessageDialog(this, "Producto agregado");
                            vistaVentas.llenarTablaproducto();

                        } else {
                            JOptionPane.showMessageDialog(this, "Producto sin Stock");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "LA CANTIDAD DEBE SER MAYOR A 0");
                    }
                }else{
                    if (dato != null) {
                        JOptionPane.showMessageDialog(this, "LA CANTIDAD NO PUEDE IR VACÍA");
                    }
                }
            }

        }
    }//GEN-LAST:event_jTableTablaProductoMouseClicked

    private void jTableTablaProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTablaProductoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableTablaProductoMousePressed

     public void llenarTablaProducto(){
        
        DefaultTableModel modelo = new DefaultTableModel(){
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return false;
            }
        };
        
        listaProductoAgregar = controladorProductoAgregar.consultaxStock();
        
        modelo.addColumn("id");
        modelo.addColumn("Nombre Producto");
        modelo.addColumn("Precio venta");
        modelo.addColumn("Stock");
        modelo.addColumn("Categoria");

        String[] datos = new String[5];
        for (Producto p : listaProductoAgregar) {
            datos[0] = p.getIdProducto()+"";
            datos[1] = p.getNombreProducto()+"";
            datos[2] = p.getPrecioVentaProducto()+"";
            datos[3] = p.getUnidsProducto()+"";
            if(p.getIdCategoria() != null){
                datos[4] = p.getIdCategoria().getNombreCategoria();
            }else{
                datos[4] = null;
            }   
            modelo.addRow(datos);
        }        
        jTableTablaProducto.setModel(modelo);
    }  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarProducto dialog = new AgregarProducto(null, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTablaProducto;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
