/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ClienteJpaController;
import controlador.DetalleVentaJpaController;
import controlador.ProductoJpaController;
import controlador.VentaJpaController;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.DetalleVenta;
import modelo.Producto;
import modelo.Usuario;
import modelo.Venta;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import reportes.Persistencia;
import templates.vistaTemplate;

/**
 *
 * @author Familia
 */
public class VistaVentas extends javax.swing.JDialog {

    public ClienteJpaController clienteControlador= new ClienteJpaController();
    public List<DetalleVenta> detalleVenta = new ArrayList<>();
    public int totalFactura = 0;
    public Usuario logueado;
    public VentaJpaController ventaControlador = new VentaJpaController();
    public DetalleVentaJpaController detalleControlador = new DetalleVentaJpaController();
    public ProductoJpaController productoControlador = new ProductoJpaController();
    int posicion = 0;
    DetalleVenta detalleSeleccionado;
    Icon iconoMostrar;
    public vistaTemplate vistaImg = new vistaTemplate();
    
    public VistaVentas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();        
        this.setTitle("VENTANA VENTAS");
        this.setLocationRelativeTo(VistaVentas.this);//para que aparezca centrado
        this.setResizable(false);//para que no se modifique el tamaño del frame
        fecha_venta.setDate(new Date());        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaObservacion = new javax.swing.JTextArea();
        jComboBoxTipoPago = new javax.swing.JComboBox<>();
        jButtonDescuento = new javax.swing.JButton();
        txtIVA = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButtonEditar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableDetalle = new javax.swing.JTable();
        btnDevuelta = new javax.swing.JButton();
        fecha_venta = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        btnCrear.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 16)); // NOI18N
        btnCrear.setText("REGISTRAR VENTA");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 16)); // NOI18N
        btnLimpiar.setText("LIMPIAR TODO");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));

        jLabel2.setBackground(new java.awt.Color(255, 102, 102));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/venta.png"))); // NOI18N
        jLabel2.setText("GESTIÓN DE VENTAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/remove.png"))); // NOI18N
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 16)); // NOI18N
        jLabel1.setText("Fecha venta:");

        txtTotal.setEnabled(false);

        txtSaldo.setText("0");
        txtSaldo.setEnabled(false);
        txtSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 16)); // NOI18N
        jLabel3.setText("Total:");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 16)); // NOI18N
        jLabel4.setText("Saldo:");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 16)); // NOI18N
        jLabel5.setText("Descuento:");

        txtDescuento.setText("0");
        txtDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescuentoKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 16)); // NOI18N
        jLabel6.setText("Tipo pago:");

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 16)); // NOI18N
        jLabel7.setText("Observaciones:");

        txtAreaObservacion.setColumns(20);
        txtAreaObservacion.setRows(5);
        txtAreaObservacion.setText("Sin observaciones.");
        jScrollPane2.setViewportView(txtAreaObservacion);

        jComboBoxTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "CONTADO", "CREDITO" }));
        jComboBoxTipoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoPagoActionPerformed(evt);
            }
        });

        jButtonDescuento.setText("A");
        jButtonDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDescuentoActionPerformed(evt);
            }
        });

        txtIVA.setEnabled(false);

        txtCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClienteFocusLost(evt);
            }
        });
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });
        txtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClienteKeyTyped(evt);
            }
        });

        txtNombre.setEnabled(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtTelefono.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 16)); // NOI18N
        jLabel11.setText("IVA(19%)");

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 16)); // NOI18N
        jLabel12.setText("Cliente:");

        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 16)); // NOI18N
        jLabel13.setText("Nombre:");

        jLabel14.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 16)); // NOI18N
        jLabel14.setText("telefono:");

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jTableDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Producto", "Precio", "Cantidad", "Sub Total", "Descuento", "Total"
            }
        ));
        jTableDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableDetalleMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTableDetalle);

        btnDevuelta.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 16)); // NOI18N
        btnDevuelta.setText("CALCULAR DEVUELTA");
        btnDevuelta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevueltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(fecha_venta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(32, 32, 32)
                        .addComponent(jComboBoxTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombre)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDevuelta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(fecha_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jComboBoxTipoPago)
                                .addGap(2, 2, 2)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDescuento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnDevuelta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // REGISTRAR TODA LA INFORMACION DE LA VENTA
        String combo = jComboBoxTipoPago.getSelectedItem().toString();
        String cliente = txtCliente.getText();
        
        if(combo.equals("Seleccione una opción")){
            iconoMostrar = vistaImg.iconoExcepcion("error");
            JOptionPane.showMessageDialog(null, "Debe elegir un método de pago", "ERROR", JOptionPane.INFORMATION_MESSAGE, iconoMostrar);            
        }else if(cliente.equals("")){
            iconoMostrar = vistaImg.iconoExcepcion("error");
            JOptionPane.showMessageDialog(null, "Debe escribir el número de cédula del cliente, si el cliente no es frecuente digite 1", "ERROR", JOptionPane.INFORMATION_MESSAGE, iconoMostrar);
        }else{
            // Buscar el cliente        
            int cedula = Integer.parseInt(txtCliente.getText());
            Cliente clienteConsultado = clienteControlador.consultarxCedula(cedula);
            if(clienteConsultado == null){
                iconoMostrar = vistaImg.iconoExcepcion("error");
                JOptionPane.showMessageDialog(null, "El cliente que está ingresando no exite", "ERROR", JOptionPane.INFORMATION_MESSAGE, iconoMostrar);
            }else if("".equals(txtTotal.getText()) || "0".equals(txtTotal.getText())){
                iconoMostrar = vistaImg.iconoExcepcion("error");
                JOptionPane.showMessageDialog(null, "Debe ingresar productos para crear la venta", "ERROR", JOptionPane.INFORMATION_MESSAGE, iconoMostrar);
            }else{
                Venta nuevaVenta = new Venta();
                nuevaVenta.setFechaVenta(fecha_venta.getDate());
                nuevaVenta.setTotalVenta(Integer.parseInt(txtTotal.getText()));
                nuevaVenta.setSaldoVenta(Integer.parseInt(txtSaldo.getText()));
                nuevaVenta.setDescuentoVenta(Integer.parseInt(txtDescuento.getText()));
                nuevaVenta.setIvaVenta(Integer.parseInt(txtIVA.getText()));
                /**********************************************************************************************/
                String observa = txtAreaObservacion.getText();
                if("".equals(observa)){
                    observa = "Sin observaciones.";
                }
                /**********************************************************************************************/
                nuevaVenta.setObservacionesVentas(observa);
                nuevaVenta.setTipoPagoVenta(jComboBoxTipoPago.getSelectedItem().toString());
                nuevaVenta.setIdCliente(clienteConsultado);
                nuevaVenta.setCodigoUsuario(logueado);
                int codigoVenta = ventaControlador.create2(nuevaVenta);
                Venta ventaCreada = ventaControlador.findVenta(codigoVenta);
                for (DetalleVenta detalle : detalleVenta) {
                    detalle.setIdVenta(ventaCreada);
                    detalleControlador.create(detalle);
                }
                iconoMostrar = vistaImg.iconoExcepcion("success");
                JOptionPane.showMessageDialog(null, "Venta registrada con éxito", "MENSAJE DE INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE, iconoMostrar);
                limpiar();
                generarFactura(codigoVenta);   
            }
        }
        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoActionPerformed

    private void jButtonDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDescuentoActionPerformed
        // Aplicar el descuento
        int descuento = Integer.parseInt(txtDescuento.getText());
        if(descuento>0 && descuento<=100){
            totalFactura = totalFactura - totalFactura*descuento/100;
            txtTotal.setText(totalFactura+"");
            txtIVA.setText((int)(totalFactura*0.19)+"");
            validarTipo();
        }else{
            iconoMostrar = vistaImg.iconoExcepcion("error");
            JOptionPane.showMessageDialog(null, "Descuento Incorrecto. Debe estar entre 1 y 100", "ERROR", JOptionPane.INFORMATION_MESSAGE, iconoMostrar);
        }
    }//GEN-LAST:event_jButtonDescuentoActionPerformed

    private void txtClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClienteFocusLost
        
        try {
            
            // Buscar el cliente
            int cedula = Integer.parseInt(txtCliente.getText());
            Cliente clienteConsultado = clienteControlador.consultarxCedula(cedula);
            if(clienteConsultado != null){
                txtNombre.setText(clienteConsultado.getNombreCliente());
                txtTelefono.setText(clienteConsultado.getTelefonoCliente());
            }else{
                iconoMostrar = vistaImg.iconoExcepcion("error");
                JOptionPane.showMessageDialog(null, "Cliente no registrado", "ERROR", JOptionPane.INFORMATION_MESSAGE, iconoMostrar);
            }
            
        }catch(NumberFormatException e){
            iconoMostrar = vistaImg.iconoExcepcion("error");
            JOptionPane.showMessageDialog(null, "Por favor no ingrese puntos, espacios, comas o letras. Solo números", "ERROR", JOptionPane.INFORMATION_MESSAGE, iconoMostrar);
        }        
        
    }//GEN-LAST:event_txtClienteFocusLost

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // REGISTRAR TODA LA INFORMACION DE LA VENTA
        detalleVenta.remove(posicion);
        llenarTablaproducto();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        // llamar la ventana que agrega los productos                
        AgregarProducto agregarProducto = new AgregarProducto(this, false);
        agregarProducto.setVisible(true);
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed

        try{
            int cant = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la nueva cantidad"));
            int id = detalleSeleccionado.getIdProducto().getIdProducto();
            Producto productoComprar = productoControlador.findProducto(id);
            if(productoComprar.getUnidsProducto() >= cant){
                //se modifica a la venta
                detalleSeleccionado.setCantidadDetalle(cant);
                detalleSeleccionado.setIdProducto(productoComprar);
                try{
                    int descuento = Integer.parseInt(JOptionPane.showInputDialog("Si tiene algun descuento, Agregelo"));
                    detalleSeleccionado.setDescuentoDetalle(descuento);
                } catch (NumberFormatException e) {
                    detalleSeleccionado.setDescuentoDetalle(0);
                }
                detalleVenta.set(posicion, detalleSeleccionado);
                //detalleVenta.remove(posicion)
                //para eliminar
                iconoMostrar = vistaImg.iconoExcepcion("success");
                JOptionPane.showMessageDialog(null, "Producto modificado", "MENSAJE DE INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE, iconoMostrar);
                llenarTablaproducto();

            }else{
                iconoMostrar = vistaImg.iconoExcepcion("error");
                JOptionPane.showMessageDialog(null, "Producto sin Stock", "ERROR", JOptionPane.INFORMATION_MESSAGE, iconoMostrar);
            }

        }catch(NumberFormatException e){
            iconoMostrar = vistaImg.iconoExcepcion("error");
            JOptionPane.showMessageDialog(null, "Por favor no ingrese puntos, espacios, comas o letras. Solo números", "ERROR", JOptionPane.INFORMATION_MESSAGE, iconoMostrar);
        }  
        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jTableDetalleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDetalleMousePressed
        // TODO add your handling code here:
        posicion = jTableDetalle.getSelectedRow();
        detalleSeleccionado = detalleVenta.get(posicion);
    }//GEN-LAST:event_jTableDetalleMousePressed

    private void jComboBoxTipoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoPagoActionPerformed
        //Acá validamos cuando el tipo de pago es de credito me lo muestr en su respectivo txt o input hablando de desarrollo web
        validarTipo();
    }//GEN-LAST:event_jComboBoxTipoPagoActionPerformed

    private void btnDevueltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevueltaActionPerformed
        
        try {
            
            String t = txtTotal.getText();
            if(!"".equals(t)){
                int total = Integer.parseInt(t);
                int valorPagoCliente = Integer.parseInt(JOptionPane.showInputDialog("¿Cuánto pagara, el cliente?"));
                int PagoActual = totalFactura;
                int totalDevuelta = valorPagoCliente - PagoActual;
                if(valorPagoCliente > PagoActual){
                    iconoMostrar = vistaImg.iconoExcepcion("success");
                JOptionPane.showMessageDialog(null, "Le devuelve $"+totalDevuelta+" pesos", "MENSAJE DE INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE, iconoMostrar);
                }else if(valorPagoCliente == PagoActual){
                    iconoMostrar = vistaImg.iconoExcepcion("success");
                JOptionPane.showMessageDialog(null, "No tiene que devolverle nada", "MENSAJE DE INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE, iconoMostrar);
                }else{
                    iconoMostrar = vistaImg.iconoExcepcion("error");
                    JOptionPane.showMessageDialog(null, "Le hace falta dinero", "ERROR", JOptionPane.INFORMATION_MESSAGE, iconoMostrar);  
                }       
            }else{
                iconoMostrar = vistaImg.iconoExcepcion("error");
                JOptionPane.showMessageDialog(null, "Para saber cuánto debe devolver debera agregar productos", "ERROR", JOptionPane.INFORMATION_MESSAGE, iconoMostrar);
            } 
        } catch(NumberFormatException e){
            iconoMostrar = vistaImg.iconoExcepcion("error");
            JOptionPane.showMessageDialog(null, "Por favor no ingrese puntos, comas o letras. Solo números", "ERROR", JOptionPane.INFORMATION_MESSAGE, iconoMostrar);
        }               
        
    }//GEN-LAST:event_btnDevueltaActionPerformed

    private void txtClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyTyped
        
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();//esto es para que solo pueda ingresar numeros
        }
        
    }//GEN-LAST:event_txtClienteKeyTyped

    private void txtDescuentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescuentoKeyTyped
        
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();//esto es para que solo pueda ingresar numeros
        }
        
    }//GEN-LAST:event_txtDescuentoKeyTyped
    
    public void limpiar(){
        
        fecha_venta.setDate(new Date());
        txtTotal.setText("0");
        txtSaldo.setText("0");
        txtDescuento.setText("0");
        jComboBoxTipoPago.setSelectedIndex(0);
        txtAreaObservacion.setText("");
        txtNombre.setText("");
        txtCliente.setText("");
        txtIVA.setText("0");
        txtTelefono.setText("");
        detalleVenta = new ArrayList<>();
        llenarTablaproducto();
        btnDevuelta.setEnabled(false);
        
    }
            
    public void llenarTablaproducto(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Producto");
        modelo.addColumn("Precio");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Sub total");
        modelo.addColumn("Descuento");
        modelo.addColumn("Total");
        String[] datos = new String[6];
        totalFactura = 0;
        for (DetalleVenta dv : detalleVenta) {
           datos[0] = dv.getIdProducto().getNombreProducto();
           datos[1] = dv.getIdProducto().getPrecioVentaProducto()+"";
           datos[2] = dv.getCantidadDetalle()+"";
           int subtotal = (dv.getIdProducto().getPrecioVentaProducto()*dv.getCantidadDetalle());
           datos[3] = subtotal+"";
           datos[4] = dv.getDescuentoDetalle()+"";
           int total = (subtotal-(subtotal*dv.getDescuentoDetalle()/100));
           totalFactura += total;
           datos[5] = total+"";
           
           modelo.addRow(datos);
        }
        txtTotal.setText(totalFactura+"");
        txtIVA.setText((int)(totalFactura*0.19)+"");
        jTableDetalle.setModel(modelo);
             
    }
    
    public void validarTipo(){
        int s = jComboBoxTipoPago.getSelectedIndex();
        if (s==2) {//CREDITO              
            txtSaldo.setText(totalFactura+"");
        }else{ //CONTADO
            txtSaldo.setText("0");
        }    
    }
    
    public void generarFactura(int numeroVenta){
    
        Map<String,Object> parametros = new HashMap<String,Object>();
        Venta ventaCreada = ventaControlador.findVenta(numeroVenta);
        parametros.put("numeroVenta", numeroVenta);
        parametros.put("cliente", ventaCreada.getIdCliente().getNombreCliente());
        parametros.put("documento", Integer.parseInt(ventaCreada.getIdCliente().getCedulaCliente().toString()));
        parametros.put("total", ventaCreada.getTotalVenta());
        parametros.put("iva", ventaCreada.getIvaVenta());
         if (Persistencia.conectar()) {
            try {
                JasperReport jr = (JasperReport) JRLoader.loadObjectFromFile("C:\\Users\\usuario\\Documents\\impre\\ServiEgo\\src\\reportes\\reporteFactura.jasper");
                JasperPrint jasperPrint = JasperFillManager.fillReport(jr, parametros, Persistencia.con);
                JasperViewer jv = new JasperViewer(jasperPrint, false);
                jv.setVisible(true);
                jv.setAlwaysOnTop(true);
                jv.setTitle("Factura de ventas");
            } catch (JRException ex) {
                Logger.getLogger(VistaVentas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaVentas dialog = new VistaVentas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnDevuelta;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRemove;
    private com.toedter.calendar.JDateChooser fecha_venta;
    private javax.swing.JButton jButtonDescuento;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JComboBox<String> jComboBoxTipoPago;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableDetalle;
    private javax.swing.JTextArea txtAreaObservacion;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtIVA;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
